spring:
  datasource:
    url: jdbc:mysql://111.230.34.189:3306/gas_station?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
jwt:
  header: Authorization
  # 令牌前缀
  token-start-with: Bearer
  # 使用Base64对该令牌进行编码
  base64-secret: Ay6tP1aHEyHLn8RffQsVjPIf+y0a0aO/4gdAf1u5qFXjx/rtF1O9TX7Xe3AbAlz8hA7oRxFT9lWfsc5d9u5cJg==
  # 令牌过期时间 此处单位/毫秒
  token-validity-in-seconds: 14400000
  logging:
    level:
      com.baomidou.mybatisplus.core: DEBUG  # 打印 MyBatis-Plus 的日志
      org.mybatis: DEBUG                    # 打印 MyBatis 的日志
server:
  port: 9090
#  ssl:
#    key-store: classpath:keystore.jks
#    key-store-password: gas_station
#    key-alias: mykey
#    key-store-type: JKS
#    enabled-protocols: TLSv1.2, TLSv1.3
